name: Mintlify Multirepo Action
description: Combine multiple Mintlify docs repositories
inputs:
  repos:
    description: >
      A stringified yaml array containing objects representing the mintlify docs
      repositories to be aggregated.
    required: true
  token:
    description: Personal access token (PAT) used to push the aggregated docs
    required: true
  target-branch:
    description: The branch to which the complete documentation will be pushed
    required: false
    default: main
  subdirectory:
    description: Path to the directory containing the main docs.json
    required: false
    default: '.'
  force:
    description: If `true`, will force-push to `target-branch`
    required: false
    default: false
runs:
  using: node20
  main: dist/index.js
